### PR TITLE
Always send requests over HTTPS

### PR DESCRIPTION
**Pull request by Rowno**
The protocol relative URL is now an anti-pattern. https://twitter.com/paul_irish/status/588502455530311680

cc @calvinfo @ndhoule @yields

### CODE REVIEW

**Comment by f2prateek** [comment]
LGTM if there are no drawbacks to it (e.g. old browser compatibility?), if so we should probably update integrations for the same?

**Comment by calvinfo** [comment]
In general I'm 100% pro-TLS. I do want to bring up the fact that there's a slight downside here that we'll drop a higher percentage of data from bounces where the customer is opting for HTTP. I'm most concerned about extra RTT times to the servers in our case–considering the answers [in the doc](https://istlsfastyet.com/#faq) aren't very re-assuring to that question. 

It's a trade-off of security vs fidelity and performance. In general I'd say it's worth it, but just acknowledging the fact that we're making the trade-off for security and privacy reasons.

**Comment by Rowno** [comment]
Did we still want this? Because then I'll fix the merge conflict.

**Comment by stevenmiller888** [comment]
cc @segment-integrations/employees 

Is this good to go? Roland will fix the merge conflict if you give the go ahead.

**Comment by tsholmes** [comment]
LGTM (pending merge-confict resolution).

**Comment by stevenmiller888** [comment]
@tsholmes Should be good to go!

**Pull request merged**
