### PR TITLE
Enable retryQueue by default.

### PR DESCRIPTION
**Pull request by f2prateek**
Now that we've graduated the feature out of beta, we should enable this by default for all customers.

Existing customers will have this flag set to false (LIB-608), so that they don't notice a change in behaviour after this lands.

### CODE REVIEW

**Comment by f2prateek** [comment]
There's a risk here that we are not testing the code path where retryQueue = false diligently anymore. However given that we plan to phase the non-retryQueue branch out, I think this should be ok.

Two other ideas:
* set retryQueue in existing tests and only rely on retryQueue = true in https://github.com/segment-integrations/analytics.js-integration-segmentio/blob/master/test/index.test.js#L987
* Copy all existing tests and and run them with retryQueue = true

**Review by fathyb — APPROVED** [review]

**Comment by f2prateek** [comment]
Pinging a couple folks from destinations to get some more eyes on this.

**Comment by f2prateek** [comment]
I updated the tests to be a bit more thorough! To make sure we test both cases well, I moved the existing tests into a table driven test. There is some redundancy with the e2e tests as a result, but I wanted to avoid changing too much logic.

**Comment by f2prateek** [comment]
@fathyb could you take a second look with the updated tests and give a 👍/👎 ?

**Review by Peripheral1994 — APPROVED** [review]

**Review by fathyb — APPROVED** [review]
LGTM 👍

**Pull request merged**
