### PR TITLE
Handle 429 and 5xx HTTP errors

### PR DESCRIPTION
**Pull request by fathyb**
Currently, our retry implementations only retries on network errors, it doesn't handle HTTP errors.

---

Ref: LIB-515

### CODE REVIEW

**Comment by f2prateek** [comment]
I think we want to not retry on 4xx errors (except 429, where we should retry).

From the guidelines:

```
In general, the retry strategy should be kept simple:

1. Retry network errors (socket timed out, etc.)
2. Retry server errors (HTTP 5xx)
3. Do not retry client errors (HTTP 4xx)
  1. Except HTTP 429.

```

**Comment by fathyb** [comment]
thanks @f2prateek! it's fixed

**Comment by f2prateek** [comment]
Thanks. LGTM! Can you write up a CC ticket?

**Comment by fathyb** [comment]
@f2prateek here is it : https://segment.atlassian.net/browse/CC-1424

**Review by f2prateek — APPROVED** [review]

**Pull request merged**
